name: Freiraum
favicon: null
layout_spectrum: 0.8595352792181075
typography_spectrum: 0.25397649221122265
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9838583474047482
  lightness: 0.07516836863942444
  saturation: 0.7606274962890893
  rhythmicContrast: 0.8323550762142986
purpose: []
