name: Freiraum
favicon: null
layout_spectrum: 0
typography_spectrum: 0.28656
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c7d5ef'
    - '#004185'
    - '#57585b'
    - '#6990bc'
    - '#98b2d5'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
